image: node:20

pipelines:
  default:
    - step:
        name: Build & Push Docker Image
        size: 2x
        caches:
          - node
        services:
          - docker
        script:
          - echo "ğŸ§± Installing dependencies"
          - npm ci
          - echo "âš¡ Building React app"
          - npm run build
          - echo "ğŸ³ Building Docker image"
          - docker build -t anarocksuperadminfrontendreact/anarocksuperadminfrontend:react-host-03 .
          - echo 12345678aA@ | docker login -u anarocksuperadminfrontendreact --password-stdin
          - docker push anarocksuperadminfrontendreact/anarocksuperadminfrontend:react-host-03